-- luacheck: globals vim

return {
  "ibhagwan/fzf-lua",
  event = "BufEnter",
  cmd = { "FzfLua" },
  config = function()
    local fzf = require "fzf-lua"
    local colors = require("base16-colorscheme").colors

    vim.api.nvim_set_hl(0, "FzfLuaPreviewNormal", { bg = colors.base01, fg = colors.base05 })
    vim.api.nvim_set_hl(0, "FzfLuaPreviewBorder", { bg = colors.base01, fg = colors.base05 })

    fzf.setup {
      "telescope",
      winopts = {
        backdrop = false,
        height = 0.85,
        width = 0.80,
        row = 0.35,
        col = 0.55,
        preview = {
          border = "none",
          wrap = "nowrap",
          hidden = "hidden",
          vertical = "down:45%",
          horizontal = "right:60%",
          layout = "flex",
          flip_columns = 120,
          title = true,
          scrollbar = "float",
          scrolloff = "-2",
          scrollchars = { "█", "" },
          delay = 100,
          winopts = {
            winhl = "Normal:FzfLuaPreviewNormal,NormalNC:FzfLuaPreviewNormal,FloatBorder:FzfLuaPreviewBorder",
          },
        },
      },
      fzf_opts = {
        ["--ansi"] = true,
        ["--info"] = "inline",
        ["--height"] = "100%",
        ["--layout"] = "reverse",
        ["--border"] = "none",
      },
      keymap = {
        builtin = {
          ["<C-/>"] = "toggle-help",
          ["<C-d>"] = "preview-page-down",
          ["<C-u>"] = "preview-page-up",
          ["<C-f>"] = "preview-page-down",
          ["<C-b>"] = "preview-page-up",
          ["<S-left>"] = "preview-reset",
        },
        fzf = {
          ["ctrl-c"] = "abort",
          ["ctrl-a"] = "toggle-all",
          ["ctrl-q"] = "select-all+accept",
          ["ctrl-s"] = "toggle-sort",
          ["ctrl-j"] = "down",
          ["ctrl-k"] = "up",
        },
      },
      actions = {
        files = {
          ["default"] = fzf.actions.file_edit_or_qf,
          ["ctrl-s"] = fzf.actions.file_split,
          ["ctrl-v"] = fzf.actions.file_vsplit,
          ["ctrl-t"] = fzf.actions.file_tabedit,
          ["alt-q"] = fzf.actions.file_sel_to_qf,
        },
        buffers = {
          ["default"] = fzf.actions.buf_edit,
          ["ctrl-s"] = fzf.actions.buf_split,
          ["ctrl-v"] = fzf.actions.buf_vsplit,
          ["ctrl-t"] = fzf.actions.buf_tabedit,
          ["ctrl-d"] = fzf.actions.buf_del,
        },
      },
      defaults = {
        file_ignore_patterns = {
          "%.7z",
          "%.burp",
          "%.bz2",
          "%.cache",
          "%.class",
          "%.dll",
          "%.docx",
          "%.dylib",
          "%.epub",
          "%.exe",
          "%.flac",
          "%.ico",
          "%.ipynb",
          "%.jar",
          "%.lock",
          "%.met",
          "%.mkv",
          "%.mp4",
          "%.pdb",
          "%.pdf",
          "%.rar",
          "%.sqlite3",
          "%.tar",
          "%.tar%.gz",
          "%.zip",
          "%.dart_tool/",
          "%.git/",
          "%.gradle/",
          "%.idea/",
          "%.settings/",
          "%.storybook/",
          "%.vale/",
          "%.vscode/",
          "__pycache__/",
          "build/",
          "dist/",
          "docs/",
          "gradle/",
          "node_modules/",
          "smalljre_.+/",
          "target/",
          "vendor/",
        },
      },
      files = {
        git_icons = true,
        file_icons = true,
        color_icons = true,
        fd_opts = "--color=never --type f --hidden --follow --exclude .git",
      },
      grep = {
        rg_opts = "--column --line-number --no-heading --color=always --smart-case --max-columns=4096 -e",
      },
      buffers = {
        previewer = false,
      },
      git = {
        branches = {
          previewer = false,
        },
      },
      lsp = {
        symbols = {
          symbol_icons = {
            File = "󰈙",
            Module = "",
            Namespace = "󰦮",
            Package = "",
            Class = "󰌗",
            Method = "󰆧",
            Property = "",
            Field = "",
            Constructor = "",
            Enum = "󰒻",
            Interface = "",
            Function = "󰊕",
            Variable = "󰫧",
            Constant = "󰏿",
            String = "󰉿",
            Number = "󰎠",
            Boolean = "󱓂",
            Array = "󰅪",
            Object = "󰅩",
            Key = "󰌋",
            Null = "󰌚",
            EnumMember = "",
            Struct = "󰌗",
            Event = "",
            Operator = "󰆕",
            TypeParameter = "󰊄",
          },
        },
      },
    }
  end,
}
