$bg = rgb({{ colors.surface.dark.hex_stripped }})
$fg = rgb({{ colors.on_surface.dark.hex_stripped }})
$bright = rgb({{ colors.primary.dark.hex_stripped }})
$dim = rgb({{ colors.on_surface_variant.dark.hex_stripped }})
$blue = rgb({{ colors.primary.dark.hex_stripped }})
$yellow = rgb({{ colors.tertiary.dark.hex_stripped }})
$error = rgb({{ colors.error.dark.hex_stripped }})
