osd-color='{{colors.on_surface.dark.hex}}'
osd-border-color='{{colors.surface.dark.hex}}'
osd-shadow-color='{{colors.shadow.dark.hex}}'
script-opts-append='osc-background_color={{colors.surface.dark.hex}}'
script-opts-append='osc-title_color={{colors.primary.dark.hex}}'
script-opts-append='osc-timecode_color={{colors.on_surface.dark.hex}}'
