ignore-empty-password
daemonize
fade-in=0.7
indicator
clock
datestr=%d/%m/%Y
screenshots
show-keyboard-layout
indicator-caps-lock

# Wallpaper theme colors
bs-hl-color={{ colors.primary.dark.hex_stripped }}cc
caps-lock-bs-hl-color={{ colors.tertiary.dark.hex_stripped }}cc
caps-lock-key-hl-color={{ colors.tertiary.dark.hex_stripped }}cc
inside-color={{ colors.surface.dark.hex_stripped }}66
inside-clear-color={{ colors.surface_container_high.dark.hex_stripped }}66
inside-caps-lock-color={{ colors.tertiary_container.dark.hex_stripped }}66
inside-ver-color={{ colors.secondary_container.dark.hex_stripped }}66
inside-wrong-color={{ colors.error_container.dark.hex_stripped }}66
key-hl-color={{ colors.primary.dark.hex_stripped }}cc
layout-bg-color={{ colors.surface.dark.hex_stripped }}00
layout-text-color={{ colors.on_surface.dark.hex_stripped }}
line-color={{ colors.primary.dark.hex_stripped }}00
ring-color={{ colors.primary.dark.hex_stripped }}cc
ring-clear-color={{ colors.secondary.dark.hex_stripped }}cc
ring-caps-lock-color={{ colors.tertiary.dark.hex_stripped }}cc
ring-ver-color={{ colors.secondary.dark.hex_stripped }}cc
ring-wrong-color={{ colors.error.dark.hex_stripped }}cc
separator-color={{ colors.primary.dark.hex_stripped }}00
text-color={{ colors.on_surface.dark.hex_stripped }}
text-clear-color={{ colors.secondary.dark.hex_stripped }}
text-caps-lock-color={{ colors.tertiary.dark.hex_stripped }}
text-ver-color={{ colors.secondary.dark.hex_stripped }}
text-wrong-color={{ colors.error.dark.hex_stripped }}

font=JetBrainsMono NFM
font-size=35
indicator-idle-visible
indicator-radius=100
indicator-thickness=7

effect-blur=10x5
effect-greyscale
effect-vignette=0.5:0.5

color={{ colors.surface.dark.hex_stripped }}
layout-border-color={{ colors.outline_variant.dark.hex_stripped }}
