# Generated by Matugen. Sourced by ~/.tmux/theme/lib/themes.sh.
declare -A THEME=(
  [background]="{{colors.surface.default.hex}}"
  [foreground]="{{colors.on_surface.default.hex}}"
  [highlight]="{{colors.surface_container.default.hex}}"
  [active]="{{colors.surface_container_high.default.hex}}"
  [blue]="{{colors.primary.default.hex}}"
  [cyan]="{{colors.secondary.default.hex}}"
  [green]="{{colors.tertiary.default.hex}}"
  [red]="{{colors.error.default.hex}}"
  [yellow]="{{colors.secondary.default.hex}}"
)
