[colors.primary]
foreground = "#d5c4a1"
background = "#1d2021"

[colors.cursor]
text   = "#1d2021"
cursor = "#d5c4a1"

[colors.selection]
text       = "#ebdbb2"
background = "#45403d"

[colors.normal]
black   = "#1d2021"
red     = "#928374"
green   = "#a89984"
yellow  = "#bdae93"
blue    = "#928374"
magenta = "#a89984"
cyan    = "#bdae93"
white   = "#a89984"

[colors.bright]
black   = "#5a524c"
red     = "#928374"
green   = "#a89984"
yellow  = "#bdae93"
blue    = "#a89984"
magenta = "#bdae93"
cyan    = "#d5c4a1"
white   = "#ebdbb2"
