gui:
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#6c7086'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
  border: single
