eval "$(starship init bash)"
eval "$(fnm env --use-on-cd)"

#Aliases
alias ls="exa --group-directories-first --icons"
alias lsl="exa --group-directories-first -lh --icons"
alias ll="exa -al -g --icons"
alias tree="exa --tree --level=2 --group-directories-first --icons --ignore-glob='*node_modules*'"
alias vis="sudo nvim"
alias font-refresh="fc-cache -fv"
alias clone="git clone --depth 1"
alias merge="xrdb ~/.Xresources"
alias search="yay -s"
alias pac="sudo pacman -S"
alias install="yay -S"
alias update="yay -Syyu"
alias remove="yay -Rns"
alias clean="yay -Yc"
alias autoclean="sudo pacman -R $(pacman -Qdtq)"
alias autoremove="sudo apt-get autoremove"
alias pkglist="yay -Qe"
alias update-lock="betterlockscreen -u ~/.wallpaper.png --fx dim,pixel,blur"
alias update-time="sudo ntpd -qg"
alias refresh-mirror="sudo reflector --latest 5 --protocol https --country 'Singapore' --sort rate --save /etc/pacman.d/mirrorlist"

alias v="nvim"
alias nv="nvim"
alias vim="nvim"

alias c="clear"
alias cl="clear"
alias cdc="cd ~/.config"
alias cdp="cd ~/Projects"
alias cdd="cd ~/Database"
alias cdo="cd ~/Downloads" 
alias cddo="cd ~/DevOps" 

alias vf="nvim ~/.config/fish/config.fish"
alias sf="source ~/.config/fish/config.fish"
alias vvv="nvim ~/.config/nvim/init.lua"

alias vbs="vim ~/.bashrc"
alias sbs="source ~/.bashrc"

alias vi3="vim ~/.config/i3/config"
alias vpo="vim ~/.config/polybar/config"

alias g="git"
alias gi="git init"
alias ga="git add . "
alias gcm="git commit -a"
alias gbm="git branch -M main"
alias gpso="git push origin main"
alias gplo="git pull origin main"
alias gst="git status"
alias glg="git log"

alias yi="yarn install"
alias ys="yarn start"
alias yd="yarn dev"
alias ya="yarn add"
alias yad="yarn add -D"

alias pni="pnpm install"
alias pns="pnpm start"
alias pnd="pnpm dev"
alias pna="pnpm add"
alias pnad="pnpm add -D"

alias ni="npm install"
alias nrs="npm run start"
alias nrd="npm run dev"
alias nid="npm install --save-dev"
alias nig="npm install --location=global"
