name = "power"
name_pretty = "Power"
icon = "Arch"

[[entries]]
text = "Logout"
keyword = ["logout", "log out", "signout"]
actions = "swaymsg exit"

[[entries]]
text = "Suspend"
keyword = ["suspend", "sleep", "hibernate"]
actions = "systemctl suspend"

[[entries]]
text = "Reboot"
keyword = ["reboot", "restart"]
actions = "systemctl reboot"

[[entries]]
text = "Shutdown"
keyword = ["shutdown", "power off", "turn off"]
actions = "systemctl poweroff"
