name = "power"
name_pretty = "Power"
icon = "power"

[[entries]]
text = "Logout"
keyword = ["logout", "log out", "signout"]
value = "swaymsg exit"

[[entries]]
text = "Suspend"
keyword = ["suspend", "sleep", "hibernate"]
value = "systemctl suspend"

[[entries]]
text = "Reboot"
keyword = ["reboot", "restart"]
value = "systemctl reboot"

[[entries]]
text = "Shutdown"
keyword = ["shutdown", "power off", "turn off"]
value = "systemctl poweroff"
