[styles]

[styles.tables]
headers = { color = "Cyan1" }

[styles.cpu]
all_entry_color = "Cyan1"
avg_entry_color = "LightSalmon1"
cpu_core_colors = ["LightSalmon1", "NavajoWhite1", "LightYellow1", "Cyan1", "SkyBlue1", "Plum1"]

[styles.memory]
ram_color = "Cyan1"
swap_color = "NavajoWhite1"
gpu_colors = ["SkyBlue1", "Plum1", "LightSalmon1", "NavajoWhite1", "LightYellow1", "Cyan1"]
arc_color = "SkyBlue1"

[styles.network]
rx_color = "Cyan1"
tx_color = "LightSalmon1"

[styles.widgets]
widget_title = { color = "Cyan1" }
border_color = "Grey35"
selected_border_color = "Cyan1"
text = { color = "Cyan1" }
selected_text = { color = "Black", bg_color = "Cyan1" }

[styles.graphs]
graph_color = "Grey58"

[styles.battery]
high_battery_color = "Cyan1"
medium_battery_color = "LightYellow1"
low_battery_color = "LightSalmon1"
