[manager]
cwd = { fg = "#99FFE4" }
hovered = { fg = "#101010", bg = "#99FFE4" }
preview_hovered = { fg = "#101010", bg = "#99FFE4" }
find_keyword = { fg = "#FF8080", bold = true }
find_position = { fg = "#FFC799" }
tab_active = { fg = "#101010", bg = "#99FFE4" }
tab_inactive = { fg = "#A0A0A0", bg = "#161616" }
tab_width = 1

[status]
mode_normal = { fg = "#101010", bg = "#99FFE4", bold = true }
mode_select = { fg = "#101010", bg = "#99FFE4", bold = true }
mode_unset = { fg = "#101010", bg = "#FF8080", bold = true }
permissions_t = { fg = "#99FFE4" }
permissions_r = { fg = "#99FFE4" }
permissions_w = { fg = "#FF8080" }
permissions_x = { fg = "#FFC799" }
permissions_s = { fg = "#D5B8FF" }

[input]
border = { fg = "#99FFE4" }
title = { fg = "#99FFE4" }
value = { fg = "#A0A0A0" }
selected = { fg = "#101010", bg = "#99FFE4" }

[confirm]
border = { fg = "#FF8080" }
title = { fg = "#FF8080" }
content = { fg = "#A0A0A0" }

[picker]
border = { fg = "#99FFE4" }
active = { fg = "#99FFE4", bold = true }
inactive = { fg = "#A0A0A0" }

[tabs]
active = { fg = "#101010", bg = "#99FFE4" }
inactive = { fg = "#A0A0A0", bg = "#161616" }

[task]
border = { fg = "#99FFE4" }
title = { fg = "#99FFE4" }

[help]
border = { fg = "#99FFE4" }
title = { fg = "#99FFE4" }

[icon]
prepend_rules = []
append_rules = []

[filetype]
rules = [
  { name = "*/", fg = "#99FFE4", bold = true },
  { mime = "image/*", fg = "#D5B8FF" },
  { mime = "video/*", fg = "#FFC799" },
  { mime = "audio/*", fg = "#FFC799" },
  { mime = "archive", fg = "#FFFFFF" },
  { mime = "documents", fg = "#A0A0A0" },
  { is = "exec", fg = "#99FFE4", bold = true },
  { is = "link", fg = "#99D1FF" },
]
