[colors]
cursor=1f1d2e e0def4
foreground=e0def4
background=191724

# Normal colors
regular0=191724
regular1=eb6f92
regular2=31748f
regular3=f6c177
regular4=9ccfd8
regular5=c4a7e7
regular6=ebbcba
regular7=908caa

# Bright colors
bright0=26233a
bright1=eb6f92
bright2=31748f
bright3=f6c177
bright4=9ccfd8
bright5=c4a7e7
bright6=ebbcba
bright7=e0def4

# Extended colors
16=f6c177
17=eb6f92

selection-foreground=e0def4
selection-background=26233a
search-box-no-match=191724 eb6f92
search-box-match=e0def4 9ccfd8
jump-labels=191724 f6c177
urls=9ccfd8
