[colors.primary]
foreground = "#DEEEED"
background = "#0A0A0A"

[colors.cursor]
text    = "#0A0A0A"
cursor  = "#DEEEED"

[colors.selection]
text       = "#DEEEED"
background = "#7A7A7A"

[colors.normal]
black   = "#080808"
red     = "#D70000"
green   = "#789978"
yellow  = "#FFAA88"
blue    = "#7788AA"
magenta = "#D7007D"
cyan    = "#708090"
white   = "#DEEEED"

[colors.bright]
black   = "#444444"
red     = "#D70000"
green   = "#789978"
yellow  = "#FFAA88"
blue    = "#7788AA"
magenta = "#D7007D"
cyan    = "#708090"
white   = "#DEEEED"
