[colors]
cursor=31353f abb2bf
foreground=abb2bf
background=282c34

# Normal colors
regular0=282c34
regular1=e86671
regular2=98c379
regular3=e5c07b
regular4=61afef
regular5=c678dd
regular6=56b6c2
regular7=5c6370

# Bright colors
bright0=3b3f4c
bright1=e86671
bright2=98c379
bright3=e5c07b
bright4=61afef
bright5=c678dd
bright6=56b6c2
bright7=abb2bf

# Extended colors
16=d19a66
17=e86671

selection-foreground=abb2bf
selection-background=3b3f4c
search-box-no-match=282c34 e86671
search-box-match=abb2bf 61afef
jump-labels=282c34 e5c07b
urls=61afef
