[styles]

[styles.tables]
headers = { color = "LightSkyBlue1" }

[styles.cpu]
all_entry_color = "LightSkyBlue1"
avg_entry_color = "LightCoral"
cpu_core_colors = ["LightCoral", "NavajoWhite1", "LightGoldenrod1", "PaleGreen1", "LightSkyBlue1", "Plum1"]

[styles.memory]
ram_color = "PaleGreen1"
swap_color = "NavajoWhite1"
gpu_colors = ["LightSkyBlue1", "Plum1", "LightCoral", "NavajoWhite1", "LightGoldenrod1", "PaleGreen1"]
arc_color = "LightSkyBlue1"

[styles.network]
rx_color = "PaleGreen1"
tx_color = "LightCoral"

[styles.widgets]
widget_title = { color = "LightSkyBlue1" }
border_color = "Grey35"
selected_border_color = "LightSkyBlue1"
text = { color = "LightSkyBlue1" }
selected_text = { color = "Black", bg_color = "LightSkyBlue1" }

[styles.graphs]
graph_color = "Grey69"

[styles.battery]
high_battery_color = "PaleGreen1"
medium_battery_color = "LightGoldenrod1"
low_battery_color = "LightCoral"
