gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#a89984"
      - bold
    inactiveBorderColor:
      - "#5a524c"
    optionsTextColor:
      - "#928374"
    selectedLineBgColor:
      - "#45403d"
    cherryPickedCommitBgColor:
      - "#32302f"
    cherryPickedCommitFgColor:
      - "#a89984"
    unstagedChangesColor:
      - "#fb4934"
    defaultFgColor:
      - "#d5c4a1"
    searchingActiveBorderColor:
      - "#bdae93"
  border: single
  authorColors:
    "*": "#928374"
disableStartupPopups: true
