exec-once = gsettings set org.gnome.desktop.interface 'Tela-grey-dark'
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
exec-once = gsettings set org.gnome.desktop.interface font-name 'Adwaita Sans 11'
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
exec-once = /usr/lib/xdg-desktop-portal-hyprland &
exec-once = /usr/lib/xdg-desktop-portal &
exec-once = systemctl --user start --now hyprpolkitagent.service
exec-once = hyprpaper
exec-once = sh ~/.local/bin/random-wallpaper.sh
exec-once = hypridle
exec-once = swaync
exec-once = swayosd-server
exec-once = vicinae server
exec-once = waybar
