$terminal = ghostty
$fileManager = nemo
$menu = wofi
$browser = helium-browser

$mainMod = SUPER

bind = $mainMod, Return, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod SHIFT, Space, exec, $menu --show drun
bind = $mainMod, B, exec, $browser
bind = $mainMod Alt, L, exec, hyprlock
bind = $mainMod, F, fullscreen, 0
bind = $mainMod SHIFT, F, fullscreen, 1

bind = $mainMod, C, killactive,
bind = $mainMod ALT, Q, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, V, togglefloating,

bind = $mainMod, Space, exec, vicinae toggle
bind = $mainMod, P, exec, vicinae vicinae://launch/clipboard/history
bind = $mainMod SHIFT, P, pseudo, # dwindle
bind = $mainMod SHIFT, S, layoutmsg, togglesplit # dwindle

bind = $mainMod, G, exec, ~/.local/bin/screen-record.sh
bind = $mainMod SHIFT, G, exec, ~/.local/bin/stop-screen-record.sh
bind = $mainMod ALT, G, exec, ~/.local/bin/screen-record-area.sh
bind = $mainMod ALT, P, exec, ~/.local/bin/color-picker.sh

bind = , Print, exec, ~/.local/bin/screenshot.sh

bind = $mainMod SHIFT, N, exec, swaync-client -t -sw
bind = $mainMod ALT, N, exec, swaync-client -t --close-all

bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, J, movefocus, u
bind = $mainMod, K, movefocus, d

bind = $mainMod SHIFT, comma, movewindow, l
bind = $mainMod SHIFT, period, movewindow, r
#bind = $mainMod SHIFT, J, movewindow, u
#bind = $mainMod SHIFT, K, movewindow, d

bind = $mainMod, R, layoutmsg, colresize +conf
bind = $mainMod SHIFT, H, layoutmsg, swapcol l
bind = $mainMod SHIFT, L, layoutmsg, swapcol r

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
binde = $mainMod, equal, resizeactive, 50 0
binde = $mainMod, minus, resizeactive, -50 0
#binde = $mainMod, plus, resizeactive, 0 -10%
#binde = $mainMod, underscore, resizeactive, 0 10%

bindel = ,XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
bindel = ,XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bindel = ,XF86AudioMute, exec, swayosd-client --output-volume mute-toggle 
bindel = ,XF86AudioMicMute, exec,swayosd-client --output-volume mic-mute-toggle 
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioStop, exec, playerctl stop
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = , XF86AudioNext, exec, playerctl next
