ecosystem {
  enforce_permissions = 1
  no_donation_nag = true
  no_update_news = true
}

permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal(-hyprland)?, screencopy, allow
permission = /usr/(bin|local/bin|sbin)/hyprpm, plugin, allow
permission = /usr/(bin|local/bin|sbin)/grim, screencopy, allow
permission = /usr/(bin|local/bin|sbin)/hyprlock, screencopy, allow
permission = /usr/(bin|local/bin|sbin)/hyprpicker, screencopy, allow
permission = /usr/(bin|local/bin|sbin)/wf-recorder, screencopy, allow
