monitor=,preferred,auto,auto

general {
    gaps_in = 8
    gaps_out = 16

    border_size = 3

    col.active_border = rgba(189,174,147,1) 
    #col.inactive_border = rgba(124,111,100,1)

    resize_on_border = true

    allow_tearing = true

    layout = scrolling

    snap {
      enabled = true
    }
}

decoration {
    rounding = 5
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 1.0
    fullscreen_opacity = 1.0

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 10
        passes = 1
        vibrancy = 0.1696
    }
}

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/bind.conf
source = ~/.config/hypr/ecosystem.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/layout.conf
source = ~/.config/hypr/misc.conf
source = ~/.config/hypr/windowrule.conf
