$bg = rgb(1d2021)
$fg = rgb(ebdbb2)
$bright = rgb(fbf1c7)
$dim = rgb(a89984)
$blue = rgb(83a598)
$yellow = rgb(fabd2f)

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    color = $bg
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $blue
    inner_color = $bg
    font_color = $fg
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = $bright
    font_size = 90
    font_family = "JetBrains Mono"
    position = 0, -200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%A, %d %B %Y"
    color = $dim
    font_size = 20
    font_family = "JetBrains Mono"
    position = 0, -310
    halign = center
    valign = center
}
