[styles.tables]
headers = { color = "#d5c4a1" }

[styles.cpu]
all_entry_color = "#d5c4a1"
avg_entry_color = "#bdae93"
cpu_core_colors = [
  "#bdae93",
  "#a89984",
  "#928374",
  "#bdae93",
  "#a89984",
  "#928374",
]

[styles.memory]
ram_color = "#928374"
swap_color = "#a89984"
gpu_colors = ["#a89984", "#d5c4a1", "#bdae93", "#a89984", "#928374", "#bdae93"]
arc_color = "#a89984"

[styles.network]
rx_color = "#928374"
tx_color = "#bdae93"

[styles.widgets]
widget_title = { color = "#d5c4a1" }
border_color = "#504945"
selected_border_color = "#bdae93"
text = { color = "#d5c4a1" }
selected_text = { color = "#282828", bg_color = "#bdae93" }

[styles.graphs]
graph_color = "#a89984"

[styles.battery]
high_battery_color = "#928374"
medium_battery_color = "#bdae93"
low_battery_color = "#a89984"
