gui:
  theme:
    activeBorderColor:
      - '#b0a890'
      - bold
    inactiveBorderColor:
      - '#a89984'
    optionsTextColor:
      - '#9c9484'
    selectedLineBgColor:
      - '#45403d'
    cherryPickedCommitBgColor:
      - '#32302f'
    cherryPickedCommitFgColor:
      - '#b0a890'
    unstagedChangesColor:
      - '#fb4934'
    defaultFgColor:
      - '#d4be98'
    searchingActiveBorderColor:
      - '#c0b090'
  border: single
  authorColors:
    "*": '#9c9484'
