gui:
  theme:
    activeBorderColor:
      - '#99FFE4'
      - bold
    inactiveBorderColor:
      - '#A0A0A0'
    optionsTextColor:
      - '#99FFE4'
    selectedLineBgColor:
      - '#232323'
    cherryPickedCommitBgColor:
      - '#161616'
    cherryPickedCommitFgColor:
      - '#99FFE4'
    unstagedChangesColor:
      - '#FF8080'
    defaultFgColor:
      - '#FFFFFF'
    searchingActiveBorderColor:
      - '#FFC799'
  authorColors:
    "*": '#99FFE4'
  border: single
disableStartupPopups: true
