#!/usr/bin/env python3
"""Hyprland Lua display trials. Detached worker owns rollback, never the UI."""

import fcntl
import json
import os
import re
import signal
import subprocess
import sys
import time
from pathlib import Path

RUNTIME = (
    Path(os.environ.get("XDG_RUNTIME_DIR", f"/run/user/{os.getuid()}")) / "qs-displays"
)
SAVED = (
    Path(os.environ.get("XDG_CONFIG_HOME", str(Path.home() / ".config")))
    / "quickshell/displays.lua"
)


def hypr(*args):
    result = subprocess.run(
        ["hyprctl", *args], capture_output=True, text=True, timeout=5, check=False
    )
    if result.returncode or (args[0] == "eval" and result.stdout.strip() != "ok"):
        raise RuntimeError(result.stderr or result.stdout)
    return result.stdout


def monitors():
    if not os.environ.get("HYPRLAND_INSTANCE_SIGNATURE"):
        raise ValueError("Active Hyprland session required")
    return json.loads(hypr("-j", "monitors", "all"))


def rule(m):
    return {
        "output": m["name"],
        "mode": f"{m['width']}x{m['height']}@{m['refreshRate']}",
        "position": f"{m['x']}x{m['y']}",
        "scale": m["scale"],
        "transform": m["transform"],
    }


def validate(data, outputs):
    current = next(
        (m for m in outputs if m["name"] == data.get("output") and not m["disabled"]),
        None,
    )
    if not current:
        raise ValueError("Select a connected, enabled display")
    if current.get("mirrorOf", "none") != "none":
        raise ValueError("Mirrored displays are not supported")
    if not re.fullmatch(r"[A-Za-z0-9_.-]+", data["output"]):
        raise ValueError("Invalid output name")
    if data.get("mode") not in [
        m.removesuffix("Hz") for m in current["availableModes"]
    ]:
        raise ValueError("Select an advertised mode")
    scale = float(data["scale"])
    if not 0.5 <= scale <= 4:
        raise ValueError("Scale must be between 0.5 and 4")
    if not re.fullmatch(r"-?\d{1,5}x-?\d{1,5}", data["position"]):
        raise ValueError("Position must be XxY, e.g. 0x0 or 1920x0")
    transform = int(data["transform"])
    if transform not in range(8):
        raise ValueError("Invalid rotation")
    return {
        "output": data["output"],
        "mode": data["mode"],
        "position": data["position"],
        "scale": scale,
        "transform": transform,
    }


def lua(data):
    return (
        "hl.monitor { "
        + ", ".join(f"{key} = {json.dumps(value)}" for key, value in data.items())
        + " }"
    )


def write_state(data):
    temp = RUNTIME / "status.tmp"
    temp.write_text(json.dumps(data))
    temp.replace(RUNTIME / "status.json")


def state():
    try:
        return json.loads((RUNTIME / "status.json").read_text())
    except FileNotFoundError:
        return {"pending": False, "message": "Ready"}


def worker(data):
    with (RUNTIME / "lock").open("w") as lock:
        try:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        except BlockingIOError:
            return
        message = "Trial interrupted; settings reverted"
        previous = None
        kept = False
        try:
            outputs = monitors()
            requested = validate(data, outputs)
            previous = rule(
                next(m for m in outputs if m["name"] == requested["output"])
            )
            decision = RUNTIME / "decision"
            decision.unlink(missing_ok=True)
            deadline = time.time() + 20
            expires = time.monotonic() + 20
            write_state(
                {
                    "pending": True,
                    "deadline": deadline,
                    "message": "Keep these settings?",
                }
            )
            hypr("eval", lua(requested))
            while time.monotonic() < expires:
                if decision.exists():
                    choice = decision.read_text()
                    if choice in ("keep", "save"):
                        if choice == "save":
                            # Save full active layout only after explicit confirmation.
                            active = [m for m in monitors() if not m["disabled"]]
                            if any(m.get("mirrorOf", "none") != "none" for m in active):
                                raise ValueError(
                                    "Saving mirrored layouts is not supported"
                                )
                            layout = [rule(m) for m in active]
                            SAVED.parent.mkdir(parents=True, exist_ok=True)
                            temp = SAVED.with_suffix(".tmp")
                            temp.write_text(
                                "-- Generated by Quickshell display settings.\n"
                                + "\n".join(lua(m) for m in layout)
                                + "\n"
                            )
                            temp.replace(SAVED)
                        kept = True
                    break
                time.sleep(0.2)
            message = "Settings saved" if kept else "Settings reverted"
        except (
            OSError,
            ValueError,
            RuntimeError,
            KeyError,
            TypeError,
            subprocess.SubprocessError,
        ) as error:
            message = str(error)
        finally:
            if previous and not kept:
                try:
                    hypr("eval", lua(previous))
                except (
                    OSError,
                    ValueError,
                    RuntimeError,
                    KeyError,
                    TypeError,
                    subprocess.SubprocessError,
                ) as error:
                    message = "Rollback failed: " + str(error)
            write_state({"pending": False, "message": message})


def main():
    RUNTIME.mkdir(mode=0o700, parents=True, exist_ok=True)
    command = sys.argv[1]
    if command == "list":
        print(json.dumps(monitors()))
    elif command == "status":
        print(json.dumps(state()))
    elif command == "apply":
        data = validate(json.loads(sys.argv[2]), monitors())
        subprocess.Popen(
            [sys.executable, __file__, "worker", json.dumps(data)],
            start_new_session=True,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    elif command == "worker":
        # Parent shell death cannot cancel the deadline. SIGTERM still rolls back.
        signal.signal(signal.SIGTERM, lambda *_: sys.exit(1))
        worker(json.loads(sys.argv[2]))
    elif command in ("keep", "save", "revert"):
        if state().get("pending"):
            (RUNTIME / "decision").write_text(command)
    else:
        raise ValueError("Unknown command")


if __name__ == "__main__":
    try:
        main()
    except (
        OSError,
        ValueError,
        RuntimeError,
        KeyError,
        TypeError,
        subprocess.SubprocessError,
    ) as error:
        print(json.dumps({"error": str(error)}))
        sys.exit(1)
