[styles.tables]
headers = { color = "#c8ccd4" }
[styles.cpu]
all_entry_color = "#c8ccd4"
avg_entry_color = "#bf616a"
cpu_core_colors = [
  "#bf616a",
  "#d08770",
  "#ebcb8b",
  "#a3be8c",
  "#88c0d0",
  "#8fbcbb",
]
[styles.memory]
ram_color = "#a3be8c"
swap_color = "#d08770"
gpu_colors = ["#8fbcbb", "#b48ead", "#bf616a", "#d08770", "#ebcb8b", "#a3be8c"]
arc_color = "#89dceb"
[styles.network]
rx_color = "#a3be8c"
tx_color = "#bf616a"
[styles.widgets]
widget_title = { color = "#eceff4" }
border_color = "#3e4451"
selected_border_color = "#8fbcbb"
text = { color = "#c8ccd4" }
selected_text = { color = "#282c34", bg_color = "#8fbcbb" }
[styles.graphs]
graph_color = "#abb2bf"
[styles.battery]
high_battery_color = "#a3be8c"
medium_battery_color = "#ebcb8b"
low_battery_color = "#bf616a"
