{pkgs, ...}: {
  home.packages = with pkgs; [
    android-tools
    bat
    bottom
    cinnamon.nemo-with-extensions
    chafa
    eza
    fd
    firefox-devedition-bin-unwrapped
    fishPlugins.autopair
    fishPlugins.forgit
    fishPlugins.fzf-fish
    fishPlugins.z
    fzf
    gh-copilot
    gimp
    google-chrome
    gnome.file-roller
    insomnia
    inxi
    mpv
    pfetch
    obsidian
    openssl
    pavucontrol
    ripgrep
    stdenv.cc.cc.lib
    termius
    tlrc
    unzip
    unrar
    viewnior
    wf-recorder
    xclip
    yazi
    zed-editor
  ];
}
