[colors]
cursor=161616 FFFFFF
foreground=FFFFFF
background=101010

# Normal colors
regular0=101010
regular1=FF8080
regular2=99FFE4
regular3=FFC799
regular4=99D1FF
regular5=D5B8FF
regular6=99FFE4
regular7=A0A0A0

# Bright colors
bright0=232323
bright1=FF8080
bright2=99FFE4
bright3=FFC799
bright4=99D1FF
bright5=D5B8FF
bright6=99FFE4
bright7=FFFFFF

# Extended colors
16=FFC799
17=FF8080

selection-foreground=FFFFFF
selection-background=232323
search-box-no-match=101010 FF8080
search-box-match=FFFFFF 99D1FF
jump-labels=101010 FFC799
urls=99D1FF
