model = "kimi-k2.7-code:cloud"
model_provider = "ollama-launch"
model_catalog_json = "/home/karyana/.codex/model.json"

[marketplaces.openai-bundled]
last_updated = "2026-07-14T16:50:05Z"
source_type = "local"
source = "/home/karyana/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-14T16:28:20Z"
source_type = "local"
source = "/home/karyana/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."read-aloud@openai-bundled"]
enabled = true

[plugins."google-calendar@openai-curated"]
enabled = true

[plugins."slack@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[features]
js_repl = false

[mcp_servers.node_repl]
args = []
command = "/opt/codex-desktop/resources/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = ""
NODE_REPL_NODE_PATH = "/opt/codex-desktop/resources/node-runtime/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/home/karyana/.codex"
CODEX_HOME = "/home/karyana/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f,c8b7e809d7cf9e20a57123b2530d476ccec9a01a6230a7b2b924fea7d94d7f4a,505eba02c6eed6bcc3f2883e6c705c3377eef8c172bb2d99c909134b0da6e57d,0c77a3b75646e46fa857011b4cde14be2f580b5655461b7c0aabf54f86fc6781"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.707.31428"

[mcp_servers.node_repl.tools]

[mcp_servers.node_repl.tools.js]
approval_mode = "approve"

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = true
appearanceTheme = "dark"
model = "kimi-k2.7-code:cloud"
model_provider = "ollama-launch"
openai_base_url = "http://127.0.0.1:11434/v1/"
followUpQueueMode = "queue"

[model_providers.ollama-launch]
name = "Ollama"
base_url = "http://127.0.0.1:11434/v1/"
wire_api = "responses"

[projects."/home/karyana/.codex"]
trust_level = "trusted"

[projects."/home/karyana/Pictures/Logo/wakuwaku"]
trust_level = "trusted"
