mode: session
status_format: false
nerdfont: true
agent: pi
worktree_dir: "~/Codes/resources/worktrees"

window_prefix: "{project} 󰘬 "

files:
  copy:
    - .env
    - .env.local
  symlink:
    - node_modules

windows:
  - name: code
    panes:
      - command: lazygit
  - name: agent
    panes:
      - command: pi
        focus: true
  - name: run
    panes:
      - command: pwd
