mode: session
status_format: false
nerdfont: true
agent: pi
worktree_dir: "~/Codes/resources/worktrees"

window_prefix: "{project} 󰘬 "

windows:
  - name: editor
    panes:
      - command: nvim
        focus: true
  - name: agent
    panes:
      - command: pi
  - name: run
    panes:
