gui:
  theme:
    activeBorderColor:
      - "#a89984"
      - bold
    inactiveBorderColor:
      - "#665c54"
    optionsTextColor:
      - "#928374"
    selectedLineBgColor:
      - "#504945"
    cherryPickedCommitBgColor:
      - "#3c3836"
    cherryPickedCommitFgColor:
      - "#a89984"
    unstagedChangesColor:
      - "#bdae93"
    defaultFgColor:
      - "#d5c4a1"
    searchingActiveBorderColor:
      - "#bdae93"
  authorColors:
    "*": "#928374"
  border: "single"
disableStartupPopups: true
