[colors.primary]
foreground = "#FFFFFF"
background = "#101010"

[colors.cursor]
text = "#101010"
cursor = "#FFFFFF"

[colors.selection]
text = "#FFFFFF"
background = "#232323"

[colors.normal]
black = "#161616"
red = "#FF8080"
green = "#99FFE4"
yellow = "#FFC799"
blue = "#99D1FF"
magenta = "#D5B8FF"
cyan = "#99FFE4"
white = "#A0A0A0"

[colors.bright]
black = "#232323"
red = "#FF8080"
green = "#99FFE4"
yellow = "#FFC799"
blue = "#99D1FF"
magenta = "#D5B8FF"
cyan = "#99FFE4"
white = "#FFFFFF"
